---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testspace_rhdh_collection.test_collection_rhdh
  description: Testing RHDH
  tags:
    - ansible
    - playbook
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: dnikoloski/testing-repo-rhdh
  links:
    - url: https://devspaces.apps.sandbox-m4.g2pi.p1.openshiftapps.com/#https://github.com/dnikoloski/testing-repo-rhdh
      title: Open Ansible project in OpenShift Dev Spaces
      icon: web
spec:
  type: playbook-project
  lifecycle: production
  owner: dnikoloski
